[package]
name         = "zdu-rs"
version      = "0.1.1"
edition      = "2024"
rust-version = "1.85"
description  = "A fast disk usage analyzer, competitive with dust and pdu."
repository   = "https://github.com/lxl66566/zdu"
license      = "MIT OR Apache-2.0"
keywords     = ["command-line", "disk", "disk-usage", "du"]
categories   = ["command-line-utilities"]
include      = [
  "/LICENSE-*",
  "/README.md",
  "/build.rs",
  "/src/**",
  "/tests/**",
]

[[bin]]
name = "zdu"
path = "src/main.rs"

[[test]]
name = "integration"
path = "tests/tests.rs"

[dependencies]
chrono        = "0.4"
clap          = { version = "4", features = ["derive"] }
config-file   = "0.2"
ctrlc         = "3"
lscolors      = "0.21"
nu-ansi-term  = "0.50"
rayon         = "1"
regex         = "1"
serde         = { version = "1.0", features = ["derive"] }
serde_json    = "1.0"
stfu8         = "0.2"
terminal_size = "0.4"
thousands     = "0.2"
unicode-width = "0.2"

[dev-dependencies]
assert_cmd = "2"
tempfile   = "=3"

[build-dependencies]
clap          = { version = "4.4", features = ["derive"] }
clap_complete = "4.4"
clap_mangen   = "0.3"

[target.'cfg(not(target_has_atomic = "64"))'.dependencies]
portable-atomic = "1.4"

[target."cfg(windows)".dependencies]
filesize    = "0.2.0"
winapi-util = "0.1"

[lints.clippy]
all                     = { level = "warn", priority = -1 }
cargo                   = { level = "warn", priority = -1 }
doc_markdown            = "allow"
missing_errors_doc      = "allow"
missing_panics_doc      = "allow"
multiple_crate_versions = "allow"
pedantic                = { level = "warn", priority = -1 }
wildcard_imports        = "allow"

[lints.rust]
unsafe_code           = "allow"
unused_qualifications = "warn"

[profile.release]
strip         = true
lto           = true
codegen-units = 1
